import {
  ArrowDown,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpDown,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  Columns2,
  Copy,
  Eraser,
  Expand,
  EyeOff,
  Filter,
  FilterX,
  GripVertical,
  Minimize,
  MoreHorizontal,
  MoreVertical,
  Pencil,
  Pin,
  RotateCcw,
  Rows2,
  Rows3,
  Rows4,
  Rss,
  Save,
  Search,
  SearchX,
  X,
  XCircle,
} from 'lucide-react';

export const SRT_Default_Icons = {
  ArrowDownwardIcon: ArrowDown,
  ArrowRightIcon: ArrowRight,
  CancelIcon: XCircle,
  ChevronLeftIcon: ChevronLeft,
  ChevronRightIcon: ChevronRight,
  ClearAllIcon: Eraser,
  CloseIcon: X,
  ContentCopy: Copy,
  DensityLargeIcon: Rows2,
  DensityMediumIcon: Rows3,
  DensitySmallIcon: Rows4,
  DragHandleIcon: GripVertical,
  DynamicFeedIcon: Rss,
  EditIcon: Pencil,
  ExpandMoreIcon: ChevronDown,
  FilterAltIcon: Filter,
  FilterListIcon: Filter,
  FilterListOffIcon: FilterX,
  FirstPageIcon: ChevronsLeft,
  FullscreenExitIcon: Minimize,
  FullscreenIcon: Expand,
  KeyboardDoubleArrowDownIcon: ChevronsDown,
  LastPageIcon: ChevronsRight,
  MoreHorizIcon: MoreHorizontal,
  MoreVertIcon: MoreVertical,
  PushPinIcon: Pin,
  RestartAltIcon: RotateCcw,
  SaveIcon: Save,
  SearchIcon: Search,
  SearchOffIcon: SearchX,
  SortIcon: ArrowUpDown,
  SyncAltIcon: ArrowLeftRight,
  ViewColumnIcon: Columns2,
  VisibilityOffIcon: EyeOff,
} as const;

export type SRT_Icons = Record<keyof typeof SRT_Default_Icons, any>;
