import {
  ArrowDown,
  ArrowRight,
  X,
  XCircle,
  ChevronLeft,
  ChevronRight,
  Eraser,
  Copy,
  GripVertical,
  Rss,
  Pencil,
  ChevronDown,
  Filter,
  FilterX,
  ChevronsLeft,
  Expand,
  Minimize,
  ChevronsDown,
  ChevronsRight,
  MoreHorizontal,
  MoreVertical,
  Pin,
  RotateCcw,
  Save,
  Search,
  SearchX,
  ArrowUpDown,
  ArrowLeftRight,
  Columns2,
  EyeOff,
  Text,
} from 'lucide-react';
import { ComponentType } from 'react';

export const SRT_Default_Icons: Record<string, ComponentType<any>> = {
  ArrowDownwardIcon: ArrowDown,
  ArrowRightIcon: ArrowRight,
  CancelIcon: XCircle,
  ChevronLeftIcon: ChevronLeft,
  ChevronRightIcon: ChevronRight,
  ClearAllIcon: Eraser,
  CloseIcon: X,
  ContentCopy: Copy,
  DensityLargeIcon: Text,
  DensityMediumIcon: Text,
  DensitySmallIcon: Text,
  DragHandleIcon: GripVertical,
  DynamicFeedIcon: Rss,
  EditIcon: Pencil,
  ExpandMoreIcon: ChevronDown,
  FilterAltIcon: Filter,
  FilterListIcon: Filter,
  FilterListOffIcon: FilterX,
  FirstPageIcon: ChevronsLeft,
  FullscreenIcon: Expand,
  FullscreenExitIcon: Minimize,
  KeyboardDoubleArrowDownIcon: ChevronsDown,
  LastPageIcon: ChevronsRight,
  MoreHorizIcon: MoreHorizontal,
  MoreVertIcon: MoreVertical,
  PushPinIcon: Pin,
  RestartAltIcon: RotateCcw,
  SaveIcon: Save,
  SearchIcon: Search,
  SearchOffIcon: SearchX,
  SortIcon: ArrowUpDown,
  SyncAltIcon: ArrowLeftRight,
  ViewColumnIcon: Columns2,
  VisibilityOffIcon: EyeOff,
} as const;

export type SRT_Icons = Record<keyof typeof SRT_Default_Icons, any>;
